name: main
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve pubspec metadata
        id: pubspec
        uses: ./
        with:
          pubspec-file: ./example/pubspec.yaml
      - name: Test name
        uses: nick-fields/assert-action@v1
        with:
          expected: example_app
          actual: ${{ steps.pubspec.outputs.name }}
      - name: Test version-number
        uses: nick-fields/assert-action@v1
        with:
          expected: 2.3.45
          actual: ${{ steps.pubspec.outputs.version-number }}
      - name: Test build-number
        uses: nick-fields/assert-action@v1
        with:
          expected: 60
          actual: ${{ steps.pubspec.outputs.build-number }}